# Activate Starship
eval "$(starship init zsh)"

# Don't use the oh-my-zsh theme.
ZSH_THEME=""

# Personalized aliases, etc.
alias ..='cd ..'
alias ls='ls -G'
alias gits='git status'
alias gitb='git branch'
alias branch='git rev-parse --abbrev-ref HEAD 2> /dev/null'
alias root='git rev-parse --show-toplevel'

# List file sizes and sort!
alias duf='du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'

source "$HOME/.myrc/sshrc"
source "$HOME/.myrc/extract"

# Make sure the conda completion plugin is loaded
autoload -U compinit && compinit

# Avoid duplicates in history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# See: https://unix.stackexchange.com/a/672892
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search


# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export PATH=$PATH:~/bin
export EDITOR=vim

# A really useful command for getting syntax highlighting when sudo vim
svim () {
    sudo -E vim @$
}

function cls {
  # https://invisible-island.net/ncurses/man/clear.1.html
  # https://unix.stackexchange.com/a/375784/246718
  # Behavior of clear:
  # 1. clear scrollback if E3 cap is supported (terminal, platform specific)
  # 2. then clear visible screen
  # For some terminal 'e[3J' need to be sent explicitly to clear scrollback
  # printf '\e[3J' && clear  # scrollback is kept by `clear`
  clear && printf '\e[3J'
}

alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
